name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.3.1
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.2+1
  flutter_bloc: ^6.1.3
  sqflite: ^1.3.1+2
  equatable: ^1.2.6
  path: ^1.7.0
  connectivity: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
